---
title: "EFleming_HW1"
description: This script gives the user a small table that shows various categories of physical contact versus their perceived reaction to the COVID virus.
author:
  - name: Emerson Fleming
    url: http://umass.edu/sbs/dacss
date: 07-13-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---

```{r setup, include=FALSE}
myDataPath <- read.csv("/Applications/Summer Session II HW/DACSS601SS22021/_data/covid-responses.tab - covid-responses.tab.csv", header=TRUE) 
covid_responses <- myDataPath
head(covid_responses)
```

```{r echo=TRUE}
myDataPath <- read.csv("/Applications/Summer Session II HW/DACSS601SS22021/_data/covid-responses.tab - covid-responses.tab.csv", header=TRUE)
covid_responses <- myDataPath
require(tidyverse) #initiated tidyverse
covid_responses %>% #addressed my data set directly to begin consolidation efforts
    select(social, handshake, stores, curfew, perceivedreaction) %>% #implemented the following variables into my set
    na.omit() #omitted all of the "NA" variables.
    head(covid_responses, 10) #used the following function to generate a larger table
    covid_responses #used the following command to generate my table
knitr::opts_chunk$set(echo = FALSE)
```
