---
title: "Genovese HW1"
description: |
  This post describes Alexander Genovese's HW1
author:
  - name: Alexander Genovese
date: 07-20-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---
## I first read in the .csv file into myData
myData <- read.delim("congressional_hearings.csv", sep = ",", header=T)

## I then read the first few lines of myData through head()
head(myData)

## I used nrow to find how many rows there were
nrow(myData)
##100254

## And ncol to find how many columns
ncol(myData)
##36

## I found the column names and listed them
colnames(myData)
##[1] "id"               "source"
##[3] "CISYear"          "Unpublished"
##[5] "Chamber"          "filter_House"
##[7] "filter_Senate"    "filter_Joint"
##[9] "CISCommittee"     "Sequence"
##[11] "Month"            "Congress"
##[13] "year"             "FiscalYear"
##[15] "Days"             "Sessions"
##[17] "Committee1"       "Subcommittee1"
##[19] "Committee2"       "Subcommittee2"
##[21] "filter_Referral"  "filter_Approp"
##[23] "filter_Agency"    "filter_Program"
##[25] "filter_Admin"     "filter_Lawmaking"
##[27] "title"            "description"
##[29] "pap_majortopic"   "pap_subtopic"
##[31] "Change."          "majortopic"
##[33] "subtopic"         "ReferralBills"
##[35] "StartDate"        "AdditionalDates"

## I would use the gather() function to collect the where the bills originated into the Chamber column. I would argue that the Chambers column could be created using gather() if it was not already there. Otherwise, no. Our gather() function could look like this:
tidymyData <- gather(myData, key = "Chamber", value = "ChamberNumber", 6:8)

## I made sure that the value I was working with was an integer and then calculated the median amount of sessions it took for a bill to be passed into law.
class(myData$Sessions)
sessionMedian <- median(myData$Sessions, na.rm = TRUE)
print(sessionMedian)

## Using stackoverflow, I found a function that can generate a mode, or the value that occurs the most. After using that on the column chamber, I found that most of these laws began in the House.
class(myData$Chamber)
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x,ux)))]
}
Mode(myData$Chamber)v

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


