---
title: "hw2_SCOrtez"
description: |
##Dataset and questions/info I am interested analyzing
    
author:
  - name: Stephanie Cortez
    url: http://umass.edu/sbs/dacss
    email: scortez@umass.edu
date: 07-17-2021
output:
  distill::distill_article:
    self_contained: false
draft: true
---
## The dataset I will be analyzing is called the "2021-2022 Student Equity Needs Index (SENI) Scores for Elementary Schools," which shows scores of elementary schools (grades k-5th) in the L.A. Unified School District (LAUSD) in CA. LAUSD is the largest school district in CA and the 2nd largest school district in the U.S. in terms of number of students.
## "The SENI was implemented to create a more inclusive and holistic understanding of our students' needs, and to empower schools with additional funds to address those needs at the local level."
## I'm going to try and compare some school demographics. LAUSD consits of 6 local districts, South, East, Central, West, NW, and NE. The dataset shows percent of foster youth, homeless youth, and English learners in elementary schools. I'm curious to know how local districts within the entire district compares. 

# Importing SENIScoresElementarySchools-2021-2022 dataset
library(readr)
sENI_20212022 <- read_csv("~/GitHub/SENIScoresElementaryShools-20212022.csv")
View(sENI_20212022)
# Checked dimension of dataset. Dataset has 509 rows/observations and 45 columns/variables
dim(sENI_20212022)
[1] 509  45 

# Checking if there are any missing values
sum(is.na(sENI_20212022))
[1] 15
colSums(is.na(sENI_20212022))
                           School Year                            School Name 
                                     0                                      0 
                      Cost Center Code                                  Index 
                                     0                                      0 
                           School Type                         Board District 
                                     0                                      0 
                        Local District                              Locn Code 
                                     0                                      0 
                              CDS Code                           Total Enroll 
                                     0                                      0 
                          Foster Count                            Foster Rate 
                                     0                                      0 
                           Foster Rank                         Homeless Count 
                                     0                                      0 
                         Homeless Rate                          Homeless Rank 
                                     0                                      0 
                              EL Count                                EL Rate 
                                     0                                      0 
                               EL Rank                              SEL Count 
                                     0                                      6 
                              SEL Rate                               SEL Rank 
                                     0                                      0 
                    Unduplicated Count                      Unduplicated Rate 
                                     0                                      0 
                     Unduplicated Rank                              Susp Rate 
                                     0                                      0 
                        Susp Rate Rank                      Dibels Gr1 BM BOY 
                                     0                                      0 
                      DIBELS Gr 1 Rank                           Chronic Rate 
                                     0                                      0 
                      Chronic Abs Rank                           LI-SWD Count 
                                     0                                      0 
                           LI-SWD Rate                            LI-SWD Rank 
                                     0                                      0 
                         ISTAR 2016-17                          ISTAR 2017-18 
                                     3                                      3 
                         ISTAR 2018-19                          ISTAR 3Yr Avg 
                                     3                                      0 
                            ISTAR Rank               Asthma Age Adjusted Rate 
                                     0                                      0 
                  Asthma Severity Rank         Non-Fatal Gunshot Injury Count 
                                     0                                      0 
         Non-Fatal Gunshot Injury Rank                     Seni Score 2020-21 
                                     0                                      0 
Seni Rank for the 2021-2022 Allocation 
                                     0 
## Found that there are NO missing values in the variables I will be analyzing.

# Checking number of schools in each Local District
table(select(sENI_20212022, "Local District"))

 C  E NE NW  S  W 
93 85 67 81 85 98 
## Found there are more schools in West local district. Found 93 schools in Central district, 85 schools in East district, 67 in NE district, 85 in South District, and 98 in West district.

# Reviewing average rates of Foster, Homeless, and English Learner rates in all of school district

 summarise(sENI_20212022, mean(`Homeless Rate`))
# A tibble: 1 x 1
  `mean(\`Homeless Rate\`)`
                      <dbl>
1                   0.00870

> summarise(sENI_20212022, mean(`Foster Rate`))
# A tibble: 1 x 1
  `mean(\`Foster Rate\`)`
                    <dbl>
1                 0.00860
> summarise(sENI_20212022, mean(`EL Rate`))
# A tibble: 1 x 1
  `mean(\`EL Rate\`)`
                <dbl>
1               0.237
## Average rates within variables are low, less than 25%. Homeless Rate mean is 0.9% , Foster Rate mean is 0.9%, and English Learner Rate mean is 24%.





```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



